server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  application:
    name: service-internal-api
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: false
        use_sql_comments: false
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 15
        one-indexed-parameters: true
